timeout: 25m
options:
  machineType: E2_HIGHCPU_32
  substitution_option: ALLOW_LOOSE

steps:
  # Run the integration tests. Actual content of this job depends on the changes 
  # detected in the PR
  - name: quay.io/gravitational/teleport-buildbox:go1.17.2
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash
    args: 
      - -c
      - |
        go run ./cmd/integration-tests          \
          -target "$_BASE_BRANCH"               \
          -bucket test-logs                     \
          -build $BUILD_ID                      \
          -key-secret "$_GITHUB_DEPLOY_KEY_SRC" \
          -a "test-logs/*.json"          
    timeout: 25m
